# Generated by Django 5.2.4 on 2025-07-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_column='tag_name', max_length=200),
        ),
    ]
