# Generated by Django 5.2.4 on 2025-07-10 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_column='tag_name', max_length=200, unique=True),
        ),
    ]
