# Generated by Django 5.2.4 on 2025-07-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_tag_create_time_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_time', 'name']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
